# SPDX-FileCopyrightText: 2021 HH Partners
#
# SPDX-License-Identifier: MIT

name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: rust
      - uses: actions-rs/cargo@v1
        name: Cargo test
        if: always()
        id: test
        with:
          command: test
          args: -- --include-ignored

  Clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: rust
      - uses: actions-rs/cargo@v1
        name: Cargo clippy
        id: clippy
        with:
          command: clippy
          args: -- -D warnings

  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: rust
      - uses: actions-rs/cargo@v1
        name: Cargo fmt
        id: format
        with:
          command: fmt
          args: --all -- --check
